### PR TITLE
repl view can send commands and walk through history, clear command, …

### PR DESCRIPTION
**Pull request by selfsame**
…creating a socket repl only splits windows if there is a single group

### CODE REVIEW

**Comment by nasser** [comment]
this looks *great*. i would change the OSX clear command to ctrl+L to match a terminal, but other than that it's solid. I wonder if there's a way we could disable typing outside the prompt area? or snap the cursor to the end of the prompt area when you start typing somewhere else? that's the only serious change i can think of.

**Comment by selfsame** [comment]
so `ctrl+L` is being used as send line in OSX.  Maybe this is a good point to rethink the bindings in general? I posted a poll on clojurians to see what people normally like.

re: repl editing, will try polling the selection on update and locking input if it extends beyond the prompt

**Comment by nasser** [comment]
good point re: send line, though `CTRL+L` would only be meaningful in the REPL window. i wonder what the clojurians would say about bindings. i was just going for something super minimal, i think extempore's atom bindings were an inspiration.

**Comment by selfsame** [comment]
out of prompt editing is now disabled

**Comment by nasser** [comment]
✌🏽✌🏽✌🏽

**Pull request merged**
